name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: ["main"]
    
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v3

      - name: Upload entire repository as artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload ALL files (including index.html or your custom HTML file)
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
