name: CI - Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add your own build steps here if needed
      # For static sites, you might not need anything else

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Make sure your built site (or index.html) is in this directory

      - id: deployment
        uses: actions/deploy-pages@v4
