name: Deploy Portfolio

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './'  # Make sure your HTML file (e.g., index.html) is in the root

      - uses: actions/deploy-pages@v2
